name: task-a cd

on: [push]

jobs:
  test:
    runs-on: "ubuntu-latest"
    name: pytest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r ./task_a/requirements.txt
      - name: Run tests
        run: |
          cd task_a && pytest --cov=. --html=report.html
      - uses: actions/upload-artifact@v4
        with:
          name: task_amy-artifact
          path: report.html